Fix PR auto scaning workflow.

diff --git a/azure-pipelines/automation-pr-scan.yml b/azure-pipelines/automation-pr-scan.yml
--- a/azure-pipelines/automation-pr-scan.yml
+++ b/azure-pipelines/automation-pr-scan.yml
@@ -43,8 +43,10 @@ jobs:
         operate=false
         [[ "$date_now" > "22:00:00" ]] && operate=true
         repos="sonic-net/sonic-buildimage sonic-net/sonic-utilities sonic-net/sonic-swss sonic-net/sonic-sairedis sonic-net/sonic-swss-common sonic-net/sonic-dbsyncd sonic-net/sonic-gnmi sonic-net/sonic-host-services sonic-net/sonic-linkmgrd sonic-net/sonic-linux-kernel sonic-net/sonic-mgmt-common sonic-net/sonic-mgmt-framework sonic-net/sonic-platform-common sonic-net/sonic-platform-daemons sonic-net/sonic-py-swsssdk sonic-net/sonic-restapi sonic-net/sonic-snmpagent sonic-net/sonic-wpa-supplicant"
+        rm -rf failure_prs.log
           for repo in $repos $(EXTRA_REPOS); do
             echo ======== working for $repo ========
+            echo $repo >> failure_prs.log
             prs=$(gh pr list -A mssonicbld --label automerge -R $repo -L 100 --json body,title,url,labels,statusCheckRollup,createdAt,baseRefName)
             c=$(echo $prs | jq length)
             for ((i=0; i<$c; i++)); do
@@ -83,12 +85,17 @@ jobs:
               # merge the PR
               echo ========Merging  PR========
               if echo $title | grep "^\[submodule\]";then
-                gh pr merge --squash --admin -R $repo $url -b "$body" || true
+                output=$(gh pr merge --squash --admin -R $repo $url -b "$body" 2>&1 ) || { echo "    $url"  >> failure_prs.log ; echo "        $output"  >> failure_prs.log ; }
               else
-                gh pr merge --rebase --admin -R $repo $url || true
-                [[ "$origin_pr_id" != "" ]] && gh pr edit https://github.com/$repo/pull/$origin_pr_id --add-label "Included in $base_ref Branch" --remove-label "Created PR to $base_ref Branch,Cherry Pick Conflict_$base_ref" || true
+                if gh pr merge --rebase --admin -R $repo $url; then
+                  [[ "$origin_pr_id" != "" ]] && gh pr edit https://github.com/$repo/pull/$origin_pr_id --add-label "Included in $base_ref Branch" --remove-label "Created PR to $base_ref Branch,Cherry Pick Conflict_$base_ref"
+                else
+                  echo "    $url"  >> failure_prs.log
+                  echo "        $output"  >> failure_prs.log
+                fi
               fi
               echo ========Finished PR========
             done
           done
+        cat failure_prs.log
       displayName: scaning
