draft

diff --git a/azure-pipelines/automation-pr-scan.yml b/azure-pipelines/automation-pr-scan.yml
--- a/azure-pipelines/automation-pr-scan.yml
+++ b/azure-pipelines/automation-pr-scan.yml
@@ -2,27 +2,92 @@ trigger: none
 pr: none
 
 schedules:
-- cron: "0 0 * * *"
+- cron: "11 */2 * * *"
   branches:
     include:
     - main
   always: true
 
 jobs:
-  - job: PRChecker
-    pool: ubuntu-20.04
-    timeoutInMinutes: 60
-    steps:
-      - checkout: none
-      - script: |
-          set -ex
-          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
-          sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
-          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
-          sudo apt update
-          sudo apt install gh -y
+- job: PRChecker
+  pool: ubuntu-20.04
+  timeoutInMinutes: 60
+  steps:
+    - checkout: none
+    - script: |
+        set -ex
+        curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
+        sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
+        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
+        sudo apt update
+        sudo apt install gh -y
 
-          echo $TOKEN | gh auth login --with-token
-        env:
-          TOKEN: $(GH_TOKEN)
-        displayName: install dependencies
+        echo $TOKEN | gh auth login --with-token
+      env:
+        TOKEN: $(GH_TOKEN)
+      displayName: install dependencies
+    - script: |
+        set -e
+        # PR merge run per 2 hours
+        # Other operation run per day.
+        # Cherry pick PR:
+        # more than 3 days, comment @author to check
+        # more than 10 days, stop comment.
+        # more than 26 days, comment @author PR will be closed
+        # more than 30 days, close PR
+        date_3d_ago=$(date --date "3 day ago" -u +"%FT%TZ")
+        date_10d_ago=$(date --date "10 day ago" -u +"%FT%TZ")
+        date_26d_ago=$(date --date "26 day ago" -u +"%FT%TZ")
+        date_30d_ago=$(date --date "30 day ago" -u +"%FT%TZ")
+        date_now=$(date -u +"%T")
+        operate=false
+        [[ "$date_now" > "22:00:00" ]] && operate=true
+        repos="sonic-net/sonic-utilities sonic-net/sonic-swss sonic-net/sonic-sairedis sonic-net/sonic-swss-common"
+          for repo in $repos; do
+            echo ======== working for $repo ========
+            prs=$(gh pr list -A mssonicbld --label automerge -R $repo -L 100 --json body,title,url,labels,statusCheckRollup,createdAt)
+            c=$(echo $prs | jq length)
+            for ((i=0; i<$c; i++)); do
+              pr=$(echo $prs | jq .[$i])
+              echo $pr | jq [.[$i].url,.[$i].author.login,.[$i].labels[].name]
+              url=$(echo $pr | jq .url)
+              body=$(echo $pr | jq .body)
+              title=$(echo $pr | jq .title)
+              origin_pr_id=$(echo $title | grep -Eo "\[action\] \[PR:[0-9]*\]" | grep -Eo [0-9]* || true)
+              created_at=$(echo $pr | jq .createdAt)
+              checks=$(echo $pr | jq .statusCheckRollup)
+              cc=$(echo $checks | jq length)
+              pr_success=true
+              check_name=''
+              for ((j=0; j<$cc; j++)); do
+                check=$(echo $checks | jq .[$j])
+                [[ "$check_name" == "" ]] && check_name=$(echo $check | jq .name -r | grep -i -e "Azure.sonic" -e "sonic-net.sonic" | grep -v '(')
+                echo $check | jq [.name,.status,.conclusion]
+                echo $check | jq .name | grep -i -v -e "Azure.sonic" -e "sonic-net.sonic" &>/dev/null && { echo continue; continue; }
+                echo $check | jq .status | grep -i -e in_progress -e queued &>/dev/null && { echo continue 2; continue 2; }
+                echo $check | jq .conclusion | grep -i -e failure -e cancelled && pr_success=false
+              done
+              # rerun PR checker
+              ! pr_success && operate && [[ "$check_name" != "" ]] && gh pr comment $url --body "/azp run $check_name"
+              # If auto cherry pick PRs failed, comment in original PR and close cherry pick PR
+              if [ -n "$origin_pr_id" ] && [[ $created_at < $date_3d_ago ]] && ! $pr_success;then
+                origin_pr_url=https://github.com/$repo/pull/$origin_pr_id
+                author=$(gh pr view $origin_pr_url --json author | jq .author.login -r)
+                echo "Original author will check."
+                $operate && [[ $created_at > $date_10d_ago ]] && gh pr comment $origin_pr_url --body "@$author cherry pick PR didn't pass PR checker. Please check!!!<br>$url"
+                $operate && [[ $created_at < $date_26d_ago ]] && gh pr comment $origin_pr_url --body "@$author cherry pick PR didn't pass PR checker. Please check!!! Auto cherry pick PR will be closed in 3 days.<br>$url"
+                $operate && [[ $created_at < $date_30d_ago ]] && echo "$url Closed" && gh pr close $url
+              fi
+              ! $pr_success && continue
+              # merge the PR
+              echo ========Merging  PR========
+              if echo $title | grep "^\[submodule\]";then
+                gh pr merge --squash --admin -R $repo $url -b "$body" || true
+              else
+                gh pr merge --rebase --admin -R $repo $url || true
+              fi
+              echo ========Finished PR========
+        done
+            done
+          done
+        displayName: scaning
