Update automation-pr-scan pipeline file
1. add Azure/*msft repos.
2. use squash merge instead of rebase.

diff --git a/azure-pipelines/automation-pr-scan.yml b/azure-pipelines/automation-pr-scan.yml
--- a/azure-pipelines/automation-pr-scan.yml
+++ b/azure-pipelines/automation-pr-scan.yml
@@ -42,7 +42,7 @@ jobs:
         date_now=$(date -u +"%T")
         operate=false
         [[ "$date_now" > "22:00:00" ]] && operate=true
-        repos="sonic-net/sonic-buildimage sonic-net/sonic-utilities sonic-net/sonic-swss sonic-net/sonic-sairedis sonic-net/sonic-swss-common sonic-net/sonic-dbsyncd sonic-net/sonic-gnmi sonic-net/sonic-host-services sonic-net/sonic-linkmgrd sonic-net/sonic-linux-kernel sonic-net/sonic-mgmt-common sonic-net/sonic-mgmt-framework sonic-net/sonic-platform-common sonic-net/sonic-platform-daemons sonic-net/sonic-py-swsssdk sonic-net/sonic-restapi sonic-net/sonic-snmpagent sonic-net/sonic-wpa-supplicant"
+        repos="sonic-net/sonic-buildimage sonic-net/sonic-utilities sonic-net/sonic-swss sonic-net/sonic-sairedis sonic-net/sonic-swss-common sonic-net/sonic-dbsyncd sonic-net/sonic-gnmi sonic-net/sonic-host-services sonic-net/sonic-linkmgrd sonic-net/sonic-linux-kernel sonic-net/sonic-mgmt-common sonic-net/sonic-mgmt-framework sonic-net/sonic-platform-common sonic-net/sonic-platform-daemons sonic-net/sonic-py-swsssdk sonic-net/sonic-restapi sonic-net/sonic-snmpagent sonic-net/sonic-wpa-supplicant Azure/sonic-swss.msft Azure/sonic-sairedis.msft Azure/sonic-utilities.msft Azure/sonic-platform-daemons.msft Azure/sonic-platform-common.msft Azure/sonic-linux-kernel.msft Azure/SAI.msft Azure/sonic-buildimage-msft"
         rm -rf failure_prs.log
         rc=0
           for repo in $repos $(EXTRA_REPOS); do
@@ -92,9 +92,9 @@ jobs:
               # merge the PR
               echo ========Merging  PR========
               if echo $title | grep "^\[submodule\]";then
-                output=$(gh pr merge --squash --admin -R $repo $url -b "$body" 2>&1 ) || { echo "    $url"  >> failure_prs.log ; echo "        $output"  >> failure_prs.log ; }
+                output=$(gh pr merge --squash --admin -R $repo $url -b "$body" 2>&1) || { echo "    $url"  >> failure_prs.log ; echo "        $output"  >> failure_prs.log ; }
               else
-                if output=$(gh pr merge --rebase --admin -R $repo $url 2>&1); then
+                if output=$(gh pr merge --squash --admin -R $repo $url -b "$body" 2>&1); then
                   [[ "$origin_pr_id" != "" ]] && gh pr edit https://github.com/$repo/pull/$origin_pr_id --add-label "Included in $base_ref Branch" --remove-label "Created PR to $base_ref Branch,Cherry Pick Conflict_$base_ref"
                 else
                   echo "    $url"  >> failure_prs.log
